### ISSUE TITLE
Should the logging be structured?

### ISSUE THREAD

**Issue by rdeusser** [rdeusser/logsip#6]
I'm curious if anyone would prefer the logging output be structured in any way. I know Logrus is structured and seems to be a good selling point for it. Let me know what you guys think!

**Comment by chasinglogic** [comment]
my favorite thing about this library is that it's such a thin wrapper that I can do my own structured logging as necessary and don't have to structure it when I don't.

**Comment by rdeusser** [comment]
Good point. I'll leave it as is. Thanks!
